name: metocean-stats
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - xarray
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas>=2.2.1
  - pip
  - scipy
  - pytest
  - windrose
  - seaborn>=0.12.2
  - pyextremes
  - cartopy
  - python-docx

