name: metocean-stats
channels:
  - conda-forge
dependencies:
  - python=>3.9
  - matplotlib>=3.1
  - numpy>=1.17
  - pandas
  - pip
  - scipy
  - pytest
  - windrose
  - seaborn>=0.12.2
  - metocean-api
